apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        tier: frontend
    spec:
      containers:
      - name: api-net
        image: danielpalacios2003/urbantheater-api
        ports:
        - containerPort: 8001
