apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  externalName: db.c5g86sosm13s.us-east-1.rds.amazonaws.com
  selector:
    app: db
  type: ExternalName
status:
  loadBalancer: {}