name: Docker Image CI - V2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ECR_REPOSITORY: UrbanTheater
  EKS_CLUSTER_NAME: UrbanTheater-Cluster
  AWS_REGION: us-east-1

jobs:

  build:
  
    name: Deployment
    runs-on: ubuntu-latest

    steps:

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
          kubectl apply -f /K8s/3-secret-app.yml
          kubectl apply -f /K8s/1-mssql-deployment.yml
          kubectl apply -f /K8s/ 2-api-deployment.yml
          kubectl apply -f /K8s/2-web-deployment.yml
          
